# Generated by Django 5.0 on 2024-02-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mobile',
            table='mobile',
        ),
    ]
